{{- if .Values.externalSecrets.enabled -}}
{{- range .Values.externalSecrets.secrets -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  secretStoreRef:
    name: argocd-secrets-manager
    kind: SecretStore
  refreshInterval: {{ .refreshInterval }}
  target:
    name: {{ .targetSecretName }}
    creationPolicy: {{ .creationPolicy }}
    {{- with .template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .data }}
  data:
    {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- end }}
{{- end }}
